/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Athletic Monochrome (design.md)
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1b1b1b",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f1f1f1",
        outline: "#7e7576",
        "outline-variant": "#cfc4c5",
        "surface-tint": "#5e5e5e",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        secondary: "#5d5f5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfe0e0",
        "on-secondary-container": "#616363",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1a1c1c",
        "on-tertiary-container": "#838484",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#454747",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        background: "#f9f9f9",
        "on-background": "#1b1b1b",
        "surface-variant": "#e2e2e2",
      },
      borderRadius: {
        none: "0px",
      },
      fontFamily: {
        lexend: ["Lexend", "sans-serif"],
        sans: ["Lexend", "sans-serif"],
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        xxl: "64px",
        section: "120px",
        gutter: "24px",
        margin: "40px",
      },
      fontSize: {
        // Typography tokens (design.md) -> dùng như: text-display, text-headline-lg, ...
        display: [
          "80px",
          { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0" }],
        "body-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0" }],
        "label-bold": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "label-md": ["12px", { lineHeight: "1.0", letterSpacing: "0" }],
      },
    },
  },
  plugins: [],
}

